language: generic 
sudo: requiered
services:
  - docker

before_install:
  - docker build -t ismailhi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ismailhi/react-test npm test -- --coverage

after_success:
  - docker build -t ismailhi/multi-client ./client
  - docker build -t ismailhi/multi-nginx ./nginx
  - docker build -t ismailhi/multi-server ./server
  - docker build -t ismailhi/multi-worker ./worker
  # log-in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take docker images and push them to docker hub
  - docker push ismailhi/multi-client
  - docker push ismailhi/multi-nginx
  - docker push ismailhi/multi-server
  - docker push ismailhi/multi-worker
  

